title: Cherono Kibet # your name (or website title) here
logo: "/images/DP.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist 
  <br><br>
  A data scientist who is familiar with gathering, cleaning and organizing data
  for use by technical and non-technical personnel.
  <br><br>
  <a href="https://www.linkedin.com/in/cherono-kibet-aa26811a9">View My LinkedIn Profile</a> 
  <a href="https://github.com/CheronoK">View My Github Profile</a>

